### ISSUE TITLE
Undefined function Embed\Http\finfo_open()

### ISSUE THREAD

**Issue by ChainsawBaby** [distantnative/embed#77]
```php
Method Kirby\Embed\Html::__toString() must not throw an exception, caught Error: Call to undefined function Embed\Http\finfo_open()
```

I updated to latest version of embed, as oembed was also giving me an error.
Updated to latest version of Kirby too

![https://i.bratteng.xyz/dn/Ir2m96mUX2.png](https://i.bratteng.xyz/dn/Ir2m96mUX2.png)

**Comment by ChainsawBaby** [comment]
I also get the error from the panel, just through the api
```
{"status":"error","code":1,"message":"Method KirbyEmbedHtml::__toString() must not throw an exception, caught Error: Call to undefined function EmbedHttpfinfo_open() in file: ########/site/plugins/embed/core/core.php on line: 0"}
```

**Comment by distantnative** [comment]
This looks like the same problem #74 – have you made sure that info is activated?

**Comment by ChainsawBaby** [comment]
@distantnative I seem to have missed the package in my php. Installed it, and it's all working now

**Comment by distantnative** [comment]
Great! :)
