### ISSUE TITLE
Internet Explorer issue (I know.. I know..)

### ISSUE THREAD

**Issue by ljacobs-sml** [distantnative/embed#79]
I feel dirty even having to bring this up, but a client keeps previewing the site I'm developing for them in IE and after switching to your embed plugin over the default youtube kirby tag, they complained about the video not playing (but they hear the sound). I tried in IE11 and sure enough I got this error in the console.

I've reminded them that IE has reached it's EOL but I don't know if these old horses will take the hint. Anyway, not sure if this is a known issue or if you care to even fix an IE issue. I haven't delved any deeper into embed.js to try and figure it out myself yet.

```
SCRIPT438: Object doesn't support property or method 'remove'
embed.js (1,99)
```

If I click on SCRIPT438 it sends me to [this page](https://docs.microsoft.com/en-us/scripting/javascript/misc/object-doesn-t-support-this-property-or-method)

**Comment by ljacobs-sml** [comment]
Quick update, 30 seconds led me to a [temporary solution](http://stackoverflow.com/questions/18919560/object-doesnt-support-property-or-method-remove) that uses jquery instead of vanilla js.. I replaced this.remove() with $(this).remove() and it's working now. Not sure you want to go that route though.

**Comment by distantnative** [comment]
I see. And you are right, I don't want to switch to jQuery because of the overload. But I will consider implementing this fallback in a next update:

```javascript
if (!('remove' in Element.prototype)) {
    Element.prototype.remove = function() {
        if (this.parentNode) {
            this.parentNode.removeChild(this);
        }
    };
}
```

**Comment by distantnative** [comment]
Bugfix added to the develop branch.
